FROM ubuntu:latest
RUN apt-get -y update
RUN apt-get -y install git cmake g++ wget unzip
RUN wget -O opencv.zip https://github.com/opencv/opencv/archive/4.x.zip
RUN unzip opencv.zip
RUN mkdir -p build && cd build
RUN cmake  ../opencv-4.x
RUN cmake  ../opencv-4.x
RUN cd ..
RUN mkdir workspace && cd workspace && mkdir classifiers-constructor
COPY classifiers-constructor/dataset workspace/classifiers-constructor